/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_free_flight_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

/* quad_free_flight_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[0])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, *w5=w+5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = (2.*@0) */
  w1 = (2.* w0 );
  /* #2: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = input[2][1] */
  w3 = arg[2] ? arg[2][1] : 0;
  /* #4: @2 = (@2+@3) */
  w2 += w3;
  /* #5: @3 = input[2][2] */
  w3 = arg[2] ? arg[2][2] : 0;
  /* #6: @2 = (@2+@3) */
  w2 += w3;
  /* #7: @3 = input[2][3] */
  w3 = arg[2] ? arg[2][3] : 0;
  /* #8: @2 = (@2+@3) */
  w2 += w3;
  /* #9: @3 = 2.5 */
  w3 = 2.5000000000000000e+00;
  /* #10: @4 = (@2/@3) */
  w4  = (w2/w3);
  /* #11: @5 = input[1][0] */
  casadi_copy(arg[1], 13, w5);
  /* #12: {@6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18} = vertsplit(@5) */
  w6 = w5[0];
  w7 = w5[1];
  w8 = w5[2];
  w9 = w5[3];
  w10 = w5[4];
  w11 = w5[5];
  w12 = w5[6];
  w13 = w5[7];
  w14 = w5[8];
  w15 = w5[9];
  w16 = w5[10];
  w17 = w5[11];
  w18 = w5[12];
  /* #13: @4 = (@4*@15) */
  w4 *= w15;
  /* #14: @1 = (@1*@4) */
  w1 *= w4;
  /* #15: @19 = input[0][4] */
  w19 = arg[0] ? arg[0][4] : 0;
  /* #16: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #17: @2 = (@2/@3) */
  w2 /= w3;
  /* #18: @3 = (@2*@14) */
  w3  = (w2*w14);
  /* #19: @20 = (@19*@3) */
  w20  = (w19*w3);
  /* #20: @1 = (@1-@20) */
  w1 -= w20;
  /* #21: @20 = input[0][5] */
  w20 = arg[0] ? arg[0][5] : 0;
  /* #22: @2 = (@2*@13) */
  w2 *= w13;
  /* #23: @21 = (@20*@2) */
  w21  = (w20*w2);
  /* #24: @1 = (@1+@21) */
  w1 += w21;
  /* #25: @21 = input[0][12] */
  w21 = arg[0] ? arg[0][12] : 0;
  /* #26: @22 = 0.5 */
  w22 = 5.0000000000000000e-01;
  /* #27: @12 = (@22*@12) */
  w12  = (w22*w12);
  /* #28: @23 = (@21*@12) */
  w23  = (w21*w12);
  /* #29: @1 = (@1+@23) */
  w1 += w23;
  /* #30: @23 = input[0][11] */
  w23 = arg[0] ? arg[0][11] : 0;
  /* #31: @11 = (@22*@11) */
  w11  = (w22*w11);
  /* #32: @24 = (@23*@11) */
  w24  = (w23*w11);
  /* #33: @1 = (@1+@24) */
  w1 += w24;
  /* #34: @24 = input[0][10] */
  w24 = arg[0] ? arg[0][10] : 0;
  /* #35: @10 = (@22*@10) */
  w10  = (w22*w10);
  /* #36: @25 = (@24*@10) */
  w25  = (w24*w10);
  /* #37: @1 = (@1+@25) */
  w1 += w25;
  /* #38: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #39: @1 = (@0*@3) */
  w1  = (w0*w3);
  /* #40: @1 = (-@1) */
  w1 = (- w1 );
  /* #41: @25 = (2.*@19) */
  w25 = (2.* w19 );
  /* #42: @25 = (@25*@4) */
  w25 *= w4;
  /* #43: @1 = (@1-@25) */
  w1 -= w25;
  /* #44: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #45: @26 = (@25*@2) */
  w26  = (w25*w2);
  /* #46: @1 = (@1+@26) */
  w1 += w26;
  /* #47: @26 = (@23*@12) */
  w26  = (w23*w12);
  /* #48: @1 = (@1+@26) */
  w1 += w26;
  /* #49: @26 = (@21*@11) */
  w26  = (w21*w11);
  /* #50: @1 = (@1-@26) */
  w1 -= w26;
  /* #51: @22 = (@22*@9) */
  w22 *= w9;
  /* #52: @9 = (@24*@22) */
  w9  = (w24*w22);
  /* #53: @1 = (@1-@9) */
  w1 -= w9;
  /* #54: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #55: @1 = (@25*@3) */
  w1  = (w25*w3);
  /* #56: @9 = (2.*@20) */
  w9 = (2.* w20 );
  /* #57: @9 = (@9*@4) */
  w9 *= w4;
  /* #58: @1 = (@1-@9) */
  w1 -= w9;
  /* #59: @9 = (@0*@2) */
  w9  = (w0*w2);
  /* #60: @1 = (@1+@9) */
  w1 += w9;
  /* #61: @9 = (@24*@12) */
  w9  = (w24*w12);
  /* #62: @1 = (@1-@9) */
  w1 -= w9;
  /* #63: @9 = (@21*@10) */
  w9  = (w21*w10);
  /* #64: @1 = (@1+@9) */
  w1 += w9;
  /* #65: @9 = (@23*@22) */
  w9  = (w23*w22);
  /* #66: @1 = (@1-@9) */
  w1 -= w9;
  /* #67: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #68: @1 = (2.*@25) */
  w1 = (2.* w25 );
  /* #69: @1 = (@1*@4) */
  w1 *= w4;
  /* #70: @3 = (@20*@3) */
  w3  = (w20*w3);
  /* #71: @1 = (@1+@3) */
  w1 += w3;
  /* #72: @2 = (@19*@2) */
  w2  = (w19*w2);
  /* #73: @1 = (@1+@2) */
  w1 += w2;
  /* #74: @2 = (@24*@11) */
  w2  = (w24*w11);
  /* #75: @1 = (@1+@2) */
  w1 += w2;
  /* #76: @2 = (@23*@10) */
  w2  = (w23*w10);
  /* #77: @1 = (@1-@2) */
  w1 -= w2;
  /* #78: @2 = (@21*@22) */
  w2  = (w21*w22);
  /* #79: @1 = (@1-@2) */
  w1 -= w2;
  /* #80: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #81: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #82: output[0][5] = @7 */
  if (res[0]) res[0][5] = w7;
  /* #83: output[0][6] = @8 */
  if (res[0]) res[0][6] = w8;
  /* #84: @8 = 2.3 */
  w8 = 2.2999999999999998e+00;
  /* #85: @7 = (@8*@23) */
  w7  = (w8*w23);
  /* #86: @6 = 0.222222 */
  w6 = 2.2222222222222221e-01;
  /* #87: @6 = (@6*@18) */
  w6 *= w18;
  /* #88: @7 = (@7*@6) */
  w7 *= w6;
  /* #89: @18 = (@23*@6) */
  w18  = (w23*w6);
  /* #90: @18 = (@8*@18) */
  w18  = (w8*w18);
  /* #91: @7 = (@7-@18) */
  w7 -= w18;
  /* #92: @18 = 4.5 */
  w18 = 4.5000000000000000e+00;
  /* #93: @1 = 0.434783 */
  w1 = 4.3478260869565222e-01;
  /* #94: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #95: @2 = (@21*@17) */
  w2  = (w21*w17);
  /* #96: @2 = (@18*@2) */
  w2  = (w18*w2);
  /* #97: @7 = (@7+@2) */
  w7 += w2;
  /* #98: @2 = (@8*@21) */
  w2  = (w8*w21);
  /* #99: @3 = (@2*@17) */
  w3  = (w2*w17);
  /* #100: @7 = (@7-@3) */
  w7 -= w3;
  /* #101: @3 = (@20*@12) */
  w3  = (w20*w12);
  /* #102: @7 = (@7-@3) */
  w7 -= w3;
  /* #103: @3 = (@25*@11) */
  w3  = (w25*w11);
  /* #104: @7 = (@7+@3) */
  w7 += w3;
  /* #105: @3 = (@0*@10) */
  w3  = (w0*w10);
  /* #106: @7 = (@7+@3) */
  w7 += w3;
  /* #107: @3 = (@19*@22) */
  w3  = (w19*w22);
  /* #108: @7 = (@7-@3) */
  w7 -= w3;
  /* #109: output[0][7] = @7 */
  if (res[0]) res[0][7] = w7;
  /* #110: @7 = (@24*@6) */
  w7  = (w24*w6);
  /* #111: @7 = (@8*@7) */
  w7  = (w8*w7);
  /* #112: @3 = (@8*@24) */
  w3  = (w8*w24);
  /* #113: @3 = (@3*@6) */
  w3 *= w6;
  /* #114: @7 = (@7-@3) */
  w7 -= w3;
  /* #115: @1 = (@1*@16) */
  w1 *= w16;
  /* #116: @2 = (@2*@1) */
  w2 *= w1;
  /* #117: @7 = (@7+@2) */
  w7 += w2;
  /* #118: @21 = (@21*@1) */
  w21 *= w1;
  /* #119: @21 = (@18*@21) */
  w21  = (w18*w21);
  /* #120: @7 = (@7-@21) */
  w7 -= w21;
  /* #121: @21 = (@19*@12) */
  w21  = (w19*w12);
  /* #122: @7 = (@7+@21) */
  w7 += w21;
  /* #123: @21 = (@0*@11) */
  w21  = (w0*w11);
  /* #124: @7 = (@7+@21) */
  w7 += w21;
  /* #125: @21 = (@25*@10) */
  w21  = (w25*w10);
  /* #126: @7 = (@7-@21) */
  w7 -= w21;
  /* #127: @21 = (@20*@22) */
  w21  = (w20*w22);
  /* #128: @7 = (@7-@21) */
  w7 -= w21;
  /* #129: output[0][8] = @7 */
  if (res[0]) res[0][8] = w7;
  /* #130: @7 = (@18*@24) */
  w7  = (w18*w24);
  /* #131: @7 = (@7*@17) */
  w7 *= w17;
  /* #132: @24 = (@24*@17) */
  w24 *= w17;
  /* #133: @24 = (@8*@24) */
  w24  = (w8*w24);
  /* #134: @7 = (@7-@24) */
  w7 -= w24;
  /* #135: @24 = (@23*@1) */
  w24  = (w23*w1);
  /* #136: @8 = (@8*@24) */
  w8 *= w24;
  /* #137: @7 = (@7+@8) */
  w7 += w8;
  /* #138: @18 = (@18*@23) */
  w18 *= w23;
  /* #139: @18 = (@18*@1) */
  w18 *= w1;
  /* #140: @7 = (@7-@18) */
  w7 -= w18;
  /* #141: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #142: @7 = (@7+@12) */
  w7 += w12;
  /* #143: @11 = (@19*@11) */
  w11  = (w19*w11);
  /* #144: @7 = (@7-@11) */
  w7 -= w11;
  /* #145: @10 = (@20*@10) */
  w10  = (w20*w10);
  /* #146: @7 = (@7+@10) */
  w7 += w10;
  /* #147: @22 = (@25*@22) */
  w22  = (w25*w22);
  /* #148: @7 = (@7-@22) */
  w7 -= w22;
  /* #149: output[0][9] = @7 */
  if (res[0]) res[0][9] = w7;
  /* #150: @7 = -2 */
  w7 = -2.;
  /* #151: @7 = (@7*@6) */
  w7 *= w6;
  /* #152: @7 = (@7+@17) */
  w7 += w17;
  /* #153: @7 = (@7-@1) */
  w7 -= w1;
  /* #154: @22 = 0.4 */
  w22 = 4.0000000000000002e-01;
  /* #155: @10 = sq(@0) */
  w10 = casadi_sq( w0 );
  /* #156: @11 = sq(@19) */
  w11 = casadi_sq( w19 );
  /* #157: @10 = (@10-@11) */
  w10 -= w11;
  /* #158: @11 = sq(@20) */
  w11 = casadi_sq( w20 );
  /* #159: @10 = (@10-@11) */
  w10 -= w11;
  /* #160: @11 = sq(@25) */
  w11 = casadi_sq( w25 );
  /* #161: @10 = (@10+@11) */
  w10 += w11;
  /* #162: @10 = (@10*@15) */
  w10 *= w15;
  /* #163: @10 = (@22*@10) */
  w10  = (w22*w10);
  /* #164: @7 = (@7+@10) */
  w7 += w10;
  /* #165: @15 = (@20*@25) */
  w15  = (w20*w25);
  /* #166: @11 = (@0*@19) */
  w11  = (w0*w19);
  /* #167: @15 = (@15-@11) */
  w15 -= w11;
  /* #168: @15 = (@15*@14) */
  w15 *= w14;
  /* #169: @15 = (@22*@15) */
  w15  = (w22*w15);
  /* #170: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #171: @7 = (@7+@15) */
  w7 += w15;
  /* #172: @20 = (@20*@0) */
  w20 *= w0;
  /* #173: @25 = (@25*@19) */
  w25 *= w19;
  /* #174: @20 = (@20+@25) */
  w20 += w25;
  /* #175: @20 = (@20*@13) */
  w20 *= w13;
  /* #176: @22 = (@22*@20) */
  w22 *= w20;
  /* #177: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #178: @7 = (@7+@22) */
  w7 += w22;
  /* #179: output[0][10] = @7 */
  if (res[0]) res[0][10] = w7;
  /* #180: @7 = (2.*@6) */
  w7 = (2.* w6 );
  /* #181: @20 = (@7-@17) */
  w20  = (w7-w17);
  /* #182: @20 = (@20-@1) */
  w20 -= w1;
  /* #183: @20 = (@20+@10) */
  w20 += w10;
  /* #184: @20 = (@20+@15) */
  w20 += w15;
  /* #185: @20 = (@20+@22) */
  w20 += w22;
  /* #186: output[0][11] = @20 */
  if (res[0]) res[0][11] = w20;
  /* #187: @6 = (-@6) */
  w6 = (- w6 );
  /* #188: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #189: @6 = (@6-@17) */
  w6 -= w17;
  /* #190: @6 = (@6+@1) */
  w6 += w1;
  /* #191: @6 = (@6+@10) */
  w6 += w10;
  /* #192: @6 = (@6+@15) */
  w6 += w15;
  /* #193: @6 = (@6+@22) */
  w6 += w22;
  /* #194: output[0][12] = @6 */
  if (res[0]) res[0][12] = w6;
  /* #195: @7 = (@7+@17) */
  w7 += w17;
  /* #196: @7 = (@7+@1) */
  w7 += w1;
  /* #197: @7 = (@7+@10) */
  w7 += w10;
  /* #198: @7 = (@7+@15) */
  w7 += w15;
  /* #199: @7 = (@7+@22) */
  w7 += w22;
  /* #200: output[0][13] = @7 */
  if (res[0]) res[0][13] = w7;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_free_flight_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_free_flight_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_free_flight_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_free_flight_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_free_flight_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_free_flight_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_free_flight_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_free_flight_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_free_flight_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quad_free_flight_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_free_flight_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_free_flight_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_free_flight_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_free_flight_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_free_flight_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_free_flight_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 39;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_free_flight_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 14*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 39*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
